version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ddd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
